packages:
  - packages/**
  - examples/**
  - tests/**
  - '!**/tests/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/deploy/**'
ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - core-js
